import os
import time
def name_printer() :
    os.system('cls' if os.name == 'nt' else 'clear')
    print("__")
    print("| ")
    print("| ")
    print("| ")
    print("| ")
    print("\_")
    print("  ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___ ")
    print("|  \ ")
    print("| . ")
    print("| |\ ")
    print("| | ")
    print("\_| ")
    print("    ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  _")
    print("|  \/ ")
    print("| .  .")
    print("| |\/|")
    print("| |  |")
    print("\_|  |")
    print("      ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___")
    print("|  \/  |")
    print("| .  . |")
    print("| |\/| |")
    print("| |  | |")
    print("\_|  |_/")
    print("        ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___  ")
    print("|  \/  |  ")
    print("| .  . | _")
    print("| |\/| |/ ")
    print("| |  | | (")
    print("\_|  |_/\_")
    print("          ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___    ")
    print("|  \/  |    ")
    print("| .  . | __ ")
    print("| |\/| |/ _`")
    print("| |  | | (_|")
    print("\_|  |_/\__,")
    print("            ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___      ")
    print("|  \/  |      ")
    print("| .  . | __ _ ")
    print("| |\/| |/ _` /")
    print("| |  | | (_| \ ")
    print("\_|  |_/\__,_|")
    print("              ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___        ")
    print("|  \/  |        ")
    print("| .  . | __ _ __")
    print("| |\/| |/ _` / _")
    print("| |  | | (_| \__")
    print("\_|  |_/\__,_|__")
    print("                ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___           ")
    print("|  \/  |         | ")
    print("| .  . | __ _ ___| ")
    print("| |\/| |/ _` / __| ")
    print("| |  | | (_| \__ | ")
    print("\_|  |_/\__,_|___/ ")
    print("                   ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _  ")
    print("|  \/  |         | | ")
    print("| .  . | __ _ ___| | ")
    print("| |\/| |/ _` / __| _ ")
    print("| |  | | (_| \__ | | ")
    print("\_|  |_/\__,_|___/\_ ")
    print("                     ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _    ")
    print("|  \/  |         | |   ")
    print("| .  . | __ _ ___| |_  ")
    print("| |\/| |/ _` / __| __/ ")
    print("| |  | | (_| \__ | ||  ")
    print("\_|  |_/\__,_|___/\__\ ")
    print("                       ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _     ")
    print("|  \/  |         | |    ")
    print("| .  . | __ _ ___| |_ __")
    print("| |\/| |/ _` / __| __/ _")
    print("| |  | | (_| \__ | ||  _")
    print("\_|  |_/\__,_|___/\__\__")
    print("                        ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _       ")
    print("|  \/  |         | |      ")
    print("| .  . | __ _ ___| |_ ___ ")
    print("| |\/| |/ _` / __| __/ _ |")
    print("| |  | | (_| \__ | ||  __|")
    print("\_|  |_/\__,_|___/\__\___|")
    print("                          ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _         ")
    print("|  \/  |         | |        ")
    print("| .  . | __ _ ___| |_ ___ _ ")
    print("| |\/| |/ _` / __| __/ _ | '")
    print("| |  | | (_| \__ | ||  __| |")
    print("\_|  |_/\__,_|___/\__\___|_|")
    print("                            ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _           ")
    print("|  \/  |         | |          ")
    print("| .  . | __ _ ___| |_ ___ _ __")
    print("| |\/| |/ _` / __| __/ _ | '__")
    print("| |  | | (_| \__ | ||  __| |  ")
    print("\_|  |_/\__,_|___/\__\___|_|  ")
    print("                              ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _           __ ")
    print("|  \/  |         | |          |  ")
    print("| .  . | __ _ ___| |_ ___ _ __|  ")
    print("| |\/| |/ _` / __| __/ _ | '__|  ")
    print("| |  | | (_| \__ | ||  __| |  |  ")
    print("\_|  |_/\__,_|___/\__\___|_|  \_ ")
    print("                                 ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _           ___  ")
    print("|  \/  |         | |          |  \ ")
    print("| .  . | __ _ ___| |_ ___ _ __| .  ")
    print("| |\/| |/ _` / __| __/ _ | '__| |\ ")
    print("| |  | | (_| \__ | ||  __| |  | |  ")
    print("\_|  |_/\__,_|___/\__\___|_|  \_|  ")
    print("                                   ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _           ___  _ ")
    print("|  \/  |         | |          |  \/  ")
    print("| .  . | __ _ ___| |_ ___ _ __| .  . ")
    print("| |\/| |/ _` / __| __/ _ | '__| |\/| ")
    print("| |  | | (_| \__ | ||  __| |  | |  | ")
    print("\_|  |_/\__,_|___/\__\___|_|  \_|  | ")
    print("                                     ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _           ___  ___ ")
    print("|  \/  |         | |          |  \/  ( ")
    print("| .  . | __ _ ___| |_ ___ _ __| .  . | ")
    print("| |\/| |/ _` / __| __/ _ | '__| |\/| | ")
    print("| |  | | (_| \__ | ||  __| |  | |  | | ")
    print("\_|  |_/\__,_|___/\__\___|_|  \_|  |_| ")
    print("                                       ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _           ___  ____  ")
    print("|  \/  |         | |          |  \/  (_) ")
    print("| .  . | __ _ ___| |_ ___ _ __| .  . |_  ")
    print("| |\/| |/ _` / __| __/ _ | '__| |\/| | | ")
    print("| |  | | (_| \__ | ||  __| |  | |  | | | ")
    print("\_|  |_/\__,_|___/\__\___|_|  \_|  |_|_| ")
    print("                                         ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _           ___  ____    ")
    print("|  \/  |         | |          |  \/  (_)   ")
    print("| .  . | __ _ ___| |_ ___ _ __| .  . |_ _  ")
    print("| |\/| |/ _` / __| __/ _ | '__| |\/| | | ' ")
    print("| |  | | (_| \__ | ||  __| |  | |  | | | | ")
    print("\_|  |_/\__,_|___/\__\___|_|  \_|  |_|_|_| ")
    print("                                           ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _           ___  ____      ")
    print("|  \/  |         | |          |  \/  (_)     ")
    print("| .  . | __ _ ___| |_ ___ _ __| .  . |_ _ __ ")
    print("| |\/| |/ _` / __| __/ _ | '__| |\/| | | '_  ")
    print("| |  | | (_| \__ | ||  __| |  | |  | | | | | ")
    print("\_|  |_/\__,_|___/\__\___|_|  \_|  |_|_|_| | ")
    print("                                             ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _           ___  ____        ")
    print("|  \/  |         | |          |  \/  (_)       ")
    print("| .  . | __ _ ___| |_ ___ _ __| .  . |_ _ __   ")
    print("| |\/| |/ _` / __| __/ _ | '__| |\/| | | '_ \  ")
    print("| |  | | (_| \__ | ||  __| |  | |  | | | | | | ")
    print("\_|  |_/\__,_|___/\__\___|_|  \_|  |_|_|_| |_| ")
    print("                                               ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _           ___  ____          ")
    print("|  \/  |         | |          |  \/  (_)         ")
    print("| .  . | __ _ ___| |_ ___ _ __| .  . |_ _ __   _ ")
    print("| |\/| |/ _` / __| __/ _ | '__| |\/| | | '_ \ /  ")
    print("| |  | | (_| \__ | ||  __| |  | |  | | | | | | ( ")
    print("\_|  |_/\__,_|___/\__\___|_|  \_|  |_|_|_| |_|\_ ")
    print("                                                 ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _           ___  ____            ")
    print("|  \/  |         | |          |  \/  (_)         | ")
    print("| .  . | __ _ ___| |_ ___ _ __| .  . |_ _ __   __| ")
    print("| |\/| |/ _` / __| __/ _ | '__| |\/| | | '_ \ / _` ")
    print("| |  | | (_| \__ | ||  __| |  | |  | | | | | | (_| ")
    print("\_|  |_/\__,_|___/\__\___|_|  \_|  |_|_|_| |_|\__, ")
    print("                                                   ")
    time.sleep(0.03)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("___  ___          _           ___  ____           _ ")
    print("|  \/  |         | |          |  \/  (_)         | |")
    print("| .  . | __ _ ___| |_ ___ _ __| .  . |_ _ __   __| |")
    print("| |\/| |/ _` / __| __/ _ | '__| |\/| | | '_ \ / _` |")
    print("| |  | | (_| \__ | ||  __| |  | |  | | | | | | (_| |")
    print("\_|  |_/\__,_|___/\__\___|_|  \_|  |_|_|_| |_|\__,_|")
    print("                                                    ")

